### ISSUE TITLE
Darc fails to connect to redis when using docker

### ISSUE THREAD

**Issue by sejego** [JarryShaw/darc#196]
**Describe the bug**
I am trying to run _darc_ using docker. To use with Redis, I have pulled [redis-stack](https://redis.io/docs/install/install-stack/docker/) to use in `docker-compose`. However, both `loader` and `crawler` fail to establish the connection with the following error(s):
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/redis/connection.py", line 1454, in get_connection
    connection = self._available_connections.pop()
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/app/darc/__main__.py", line 172, in <module>
    sys.exit(main())
  File "/app/darc/__main__.py", line 101, in main
    _redis_command('set', 'darc', pid)
  File "/app/darc/db.py", line 152, in _redis_command
    value = method(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/redis/commands/core.py", line 2328, in set
    return self.execute_command("SET", *pieces, **options)
  File "/usr/local/lib/python3.9/dist-packages/redis/client.py", line 1266, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/local/lib/python3.9/dist-packages/redis/connection.py", line 1456, in get_connection
    connection = self.make_connection()
  File "/usr/local/lib/python3.9/dist-packages/redis/connection.py", line 1496, in make_connection
    return self.connection_class(**self.connection_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/redis/connection.py", line 960, in __init__
    super().__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'decode_components'
```
I confirm that the connection between Redis container and the crawler/loader containers **is present**. Both containers can ping each other. Furthermore, with Python3 interpreter I managed to create a key-value in Redis using Python - no problems encountered there either.

This is my _docker-compose.yml_:
```
version: '3'

services:
  crawler:
    image: jsnbzh/darc:latest
    build: &build
      context: .
      args:
    ##  params removed for brevity
    container_name: crawler
    #entrypoint: [ "bash", "/app/run.sh" ]
    command: [ "--type", "crawler",
               "--file", "/app/proton.txt"]
    environment:
      ##  params removed for brevity

    restart: "always"
    networks: &networks
      - darc
    volumes: &volumes
      - ./text:/app/text
      - ./extra:/app/extra
      - /home/sejego/data/darc:/app/data

  loader:
    image: jsnbzh/darc:latest
    build: *build
    container_name: loader
    #entrypoint: [ "bash", "/app/run.sh" ]
    command: [ "--type", "loader" ]
    environment:
      ##  params removed for brevity

    restart: "always"
    networks: *networks
    volumes: *volumes

  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    networks: *networks
    ports:
      - "6379:6379"
      - "8001:8001"

# network settings
networks:
  darc:
    driver: bridge
```

**To Reproduce**
1. Add _redis-stack_ image to list of services launched by _docker-compose.yml_
2. Launch containers using `docker compose up`
4. See errors created by `loader` and `crawler`

**Expected behavior**
When launched, the connection is established, and all key-values are successfully initialized in Redis by `darc`. `darc` continues to crawl/load pages.

**Screenshots**
![image](https://github.com/JarryShaw/darc/assets/38634698/55c29e2d-695f-48b2-84b5-74fbf9893c41)

**Comment by JarryShaw** [comment]
This is mainly due to the upgrade of Redis client library. I have pushed out and released a newer version to address this bug. Please kindly use the latest version (`1.0.1`).

**Comment by sejego** [comment]
Confirm that it got fixed!
